# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Move_Multiple_layer_features
                                 A QGIS plugin
 used to move multiple layers features at once.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-05-07
        copyright            : (C) 2025 by Bhavani R
        email                : rbhavani@datacollectionindia.co.in
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Move_Multiple_layer_features class from file Move_Multiple_layer_features.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Move_Multiple_layer_features import Move_Multiple_layer_features
    return Move_Multiple_layer_features(iface)
